### PR TITLE
Support Simplified Chinese

### PR DESCRIPTION
**Pull request by ghoevil**

### CODE REVIEW

**Review by keshav-space — APPROVED** [review]

**Comment by keshav-space** [comment]
Thanks @ghoevil 🙇

**Comment by keshav-space** [comment]
@ghoevil I guess we would need to provide [full_description.txt](https://github.com/keshav-space/safenotes/blob/main/fastlane/metadata/android/en-US/full_description.txt) in Chinese too

**Comment by ghoevil** [comment]
@keshav-space ok, I will make the full desc in chinese.

**Comment by keshav-space** [comment]
Thanks @ghoevil,
You can put Chinese translation for [full_description.txt](https://github.com/keshav-space/safenotes/blob/main/fastlane/metadata/android/en-US/full_description.txt) in this file [fastlane/metadata/android/zh-CN/full_description.txt](https://github.com/keshav-space/safenotes/blob/main/fastlane/metadata/android/zh-CN/full_description.txt)

**Pull request merged**
